# Auto-generated by `mr-diff --print-completion bash`. Install:
#   eval "$(mr-diff --print-completion bash)"

__mr_diff_files() {
  local cur="$1" out files
  out="$(command mr-diff list --name-only 2>/dev/null)"
  if [[ -z "$out" ]]; then
    out="$( { command git ls-files 2>/dev/null; command git \
      ls-files --others --exclude-standard 2>/dev/null; } \
      | sort -u )"
  fi
  files="$out"
  COMPREPLY=( $(compgen -W "$files" -- "$cur") )
}

_mr_diff_completion() {
  local cur cword
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  cword="$COMP_CWORD"

  if [[ "$cword" -eq 1 ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "--print-completion -h --help" \
        -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "list file" -- "$cur") )
    fi
    return 0
  fi

  if [[ "${COMP_WORDS[1]}" == "--print-completion" ]]; then
    if [[ "$cword" -eq 2 ]]; then
      COMPREPLY=( $(compgen -W "bash zsh" -- "$cur") )
    fi
    return 0
  fi

  case "${COMP_WORDS[1]}" in
    list)
      COMPREPLY=( $(compgen -W "--name-only -h --help" -- "$cur") )
      return 0
      ;;
    file)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
      elif [[ "$cword" -eq 2 ]]; then
        __mr_diff_files "$cur"
      fi
      return 0
      ;;
  esac
}

complete -F _mr_diff_completion mr-diff
