#compdef mr-diff
# Auto-generated by `mr-diff --print-completion zsh`. Install with:
#   eval "$(mr-diff --print-completion zsh)"

__mr_diff_files() {
  local -a files
  local out
  out="$(command mr-diff list --name-only 2>/dev/null)"
  if [[ -n "$out" ]]; then
    files=(${(f)out})
  else
    files=(${(f)"$(command git ls-files 2>/dev/null)"} \
      ${(f)"$(command git ls-files --others --exclude-standard \
      2>/dev/null)"})
  fi
  compadd -a files
}

_mr_diff() {
  local curcontext="$curcontext" state line
  typeset -A opt_args
  local curword
  curword="${words[CURRENT]}"

  if (( CURRENT == 2 )); then
    if [[ "$curword" == -* ]]; then
      compadd -- --print-completion -h --help
    else
      compadd -- list file
    fi
    return
  fi

  if [[ "${words[2]}" == "--print-completion" ]]; then
    if (( CURRENT == 3 )); then
      compadd -- bash zsh
    fi
    return
  fi

  case "${words[2]}" in
    list)
      [[ "$curword" == -* ]] && compadd -- --name-only -h --help
      return
      ;;
    file)
      if [[ "$curword" == -* ]]; then
        compadd -- -h --help
      elif (( CURRENT == 3 )); then
        __mr_diff_files
      fi
      return
      ;;
  esac
}

compdef _mr_diff mr-diff
