# Auto-generated by `mr --print-completion bash`. Install with:
#   eval "$(mr --print-completion bash)"

__mr_branch_refs() {
  local cur="$1" refs
  refs="$( { command git branch --format='%(refname:short)' \
    2>/dev/null; command git branch -r \
    --format='%(refname:short)' 2>/dev/null | grep -v -- ' -> '; } \
    | sort -u )"
  COMPREPLY=( $(compgen -W "$refs" -- "$cur") )
}

_mr_completion() {
  local cur prev cword
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  cword="$COMP_CWORD"

  if [[ "$cword" -eq 1 ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "--print-completion -h --help" \
        -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "new base rebase reset squash merge \
        publish config completion" -- "$cur") )
    fi
    return 0
  fi

  if [[ "${COMP_WORDS[1]}" == "--print-completion" ]]; then
    if [[ "$cword" -eq 2 ]]; then
      COMPREPLY=( $(compgen -W "bash zsh" -- "$cur") )
    fi
    return 0
  fi

  case "${COMP_WORDS[1]}" in
    new)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "--no-fetch -h --help" -- "$cur") )
      elif [[ "$cword" -eq 2 ]]; then
        COMPREPLY=()
      elif [[ "$cword" -eq 3 ]]; then
        __mr_branch_refs "$cur"
      fi
      return 0
      ;;
    base)
      if [[ "$cword" -eq 2 ]]; then
        if [[ "$cur" == -* ]]; then
          COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
        else
          COMPREPLY=( $(compgen -W "set reset default" -- "$cur") )
        fi
        return 0
      fi
      case "${COMP_WORDS[2]}" in
        set)
          if [[ "$cur" == -* ]]; then
            COMPREPLY=( $(compgen -W "--no-fetch -h --help" \
              -- "$cur") )
          elif [[ "$cword" -eq 3 ]]; then
            __mr_branch_refs "$cur"
          fi
          return 0
          ;;
        reset)
          COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
          return 0
          ;;
        default)
          if [[ "$cword" -eq 3 ]]; then
            COMPREPLY=( $(compgen -W "set reset" -- "$cur") )
            return 0
          fi
          if [[ "${COMP_WORDS[3]}" == "set" ]]; then
            if [[ "$cur" == -* ]]; then
              COMPREPLY=( $(compgen -W "--no-fetch -h --help" \
                -- "$cur") )
            elif [[ "$cword" -eq 4 ]]; then
              __mr_branch_refs "$cur"
            fi
          fi
          return 0
          ;;
      esac
      return 0
      ;;
    rebase)
      if [[ "$prev" == "--onto" ]]; then
        __mr_branch_refs "$cur"
        return 0
      fi
      COMPREPLY=( $(compgen -W "--onto --continue --skip --abort \
        --no-fetch -h --help" -- "$cur") )
      return 0
      ;;
    reset)
      COMPREPLY=( $(compgen -W "--soft --mixed --hard --no-fetch \
        -h --help" -- "$cur") )
      return 0
      ;;
    squash)
      if [[ "$prev" == "-m" || "$prev" == "--message" ]]; then
        COMPREPLY=()
        return 0
      fi
      COMPREPLY=( $(compgen -W "-m --message --no-fetch \
        -h --help" -- "$cur") )
      return 0
      ;;
    merge)
      if [[ "$prev" == "-m" || "$prev" == "--message" ]]; then
        COMPREPLY=()
        return 0
      fi
      COMPREPLY=( $(compgen -W "-m --message --squash --no-ff \
        --push --no-push --no-fetch -h --help" -- "$cur") )
      return 0
      ;;
    publish)
      case "$prev" in
        -t|--title|-d|--description|-l|--label|-a|--assignee|\
        --reviewer)
          COMPREPLY=()
          return 0
          ;;
      esac
      COMPREPLY=( $(compgen -W "--no-fetch --no-push --fill -y \
        --yes --draft -t --title -d --description -l --label -a \
        --assignee --reviewer --remove-source-branch -h --help" \
        -- "$cur") )
      return 0
      ;;
    config)
      if [[ "$cword" -eq 2 ]]; then
        COMPREPLY=( $(compgen -W "list set reset" -- "$cur") )
        return 0
      fi
      case "${COMP_WORDS[2]}" in
        set)
          if [[ "$cword" -eq 3 ]]; then
            COMPREPLY=( $(compgen -W "merge.strategy merge.push" \
              -- "$cur") )
          elif [[ "$cword" -eq 4 ]]; then
            case "${COMP_WORDS[3]}" in
              merge.strategy)
                COMPREPLY=( $(compgen -W "squash merge" -- "$cur") )
                ;;
              merge.push)
                COMPREPLY=( $(compgen -W "auto always never" \
                  -- "$cur") )
                ;;
            esac
          fi
          return 0
          ;;
        reset)
          if [[ "$cword" -eq 3 ]]; then
            COMPREPLY=( $(compgen -W "merge.strategy merge.push" \
              -- "$cur") )
          fi
          return 0
          ;;
      esac
      return 0
      ;;
    completion)
      if [[ "$cword" -eq 2 ]]; then
        if [[ "$cur" == -* ]]; then
          COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
        else
          COMPREPLY=( $(compgen -W "install uninstall status" \
            -- "$cur") )
        fi
        return 0
      fi
      case "${COMP_WORDS[2]}" in
        install)
          if [[ "$prev" == "--shell" ]]; then
            COMPREPLY=( $(compgen -W "bash zsh" -- "$cur") )
          else
            COMPREPLY=( $(compgen -W "--shell --dry-run -h --help" \
              -- "$cur") )
          fi
          return 0
          ;;
        uninstall)
          if [[ "$prev" == "--shell" ]]; then
            COMPREPLY=( $(compgen -W "bash zsh" -- "$cur") )
          else
            COMPREPLY=( $(compgen -W "--shell -h --help" -- "$cur") )
          fi
          return 0
          ;;
      esac
      return 0
      ;;
  esac
}

complete -F _mr_completion mr
