#compdef mr
# Auto-generated by `mr --print-completion zsh`. Install with:
#   eval "$(mr --print-completion zsh)"

__mr_branch_refs() {
  local -a refs
  local line
  refs=()
  for line in ${(f)"$(command git branch \
      --format='%(refname:short)' 2>/dev/null)"} \
      ${(f)"$(command git branch -r \
      --format='%(refname:short)' 2>/dev/null)"}; do
    [[ -z "$line" || "$line" == *' -> '* ]] && continue
    refs+=("$line")
  done
  refs=(${(u)refs})
  compadd -a refs
}

_mr() {
  local curcontext="$curcontext" state line
  typeset -A opt_args
  local curword
  curword="${words[CURRENT]}"

  if (( CURRENT == 2 )); then
    if [[ "$curword" == -* ]]; then
      compadd -- --print-completion -h --help
    else
      compadd -- new base rebase reset squash merge publish config completion
    fi
    return
  fi

  if [[ "${words[2]}" == "--print-completion" ]]; then
    if (( CURRENT == 3 )); then
      compadd -- bash zsh
    fi
    return
  fi

  case "${words[2]}" in
    new)
      if [[ "$curword" == -* ]]; then
        compadd -- --no-fetch -h --help
      elif (( CURRENT == 3 )); then
        return
      elif (( CURRENT == 4 )); then
        __mr_branch_refs
      fi
      return
      ;;
    base)
      if (( CURRENT == 3 )); then
        if [[ "$curword" == -* ]]; then
          compadd -- -h --help
        else
          compadd -- set reset default
        fi
        return
      fi
      case "${words[3]}" in
        set)
          if [[ "$curword" == -* ]]; then
            compadd -- --no-fetch -h --help
          elif (( CURRENT == 4 )); then
            __mr_branch_refs
          fi
          return
          ;;
        reset)
          [[ "$curword" == -* ]] && compadd -- -h --help
          return
          ;;
        default)
          if (( CURRENT == 4 )); then
            if [[ "$curword" == -* ]]; then
              compadd -- -h --help
            else
              compadd -- set reset
            fi
            return
          fi
          case "${words[4]}" in
            set)
              if [[ "$curword" == -* ]]; then
                compadd -- --no-fetch -h --help
              elif (( CURRENT == 5 )); then
                __mr_branch_refs
              fi
              ;;
            reset)
              [[ "$curword" == -* ]] && compadd -- -h --help
              ;;
          esac
          return
          ;;
      esac
      return
      ;;
    rebase)
      if [[ "${words[CURRENT-1]}" == "--onto" ]]; then
        __mr_branch_refs
        return
      fi
      if [[ "$curword" == -* || "$curword" == "" ]]; then
        compadd -- --onto --continue --skip --abort \
          --no-fetch -h --help
      fi
      return
      ;;
    reset)
      if [[ "$curword" == -* || "$curword" == "" ]]; then
        compadd -- --soft --mixed --hard --no-fetch -h --help
      fi
      return
      ;;
    squash)
      if [[ "${words[CURRENT-1]}" == "-m" || \
          "${words[CURRENT-1]}" == "--message" ]]; then
        return
      fi
      if [[ "$curword" == -* || "$curword" == "" ]]; then
        compadd -- -m --message --no-fetch -h --help
      fi
      return
      ;;
    merge)
      if [[ "${words[CURRENT-1]}" == "-m" || \
          "${words[CURRENT-1]}" == "--message" ]]; then
        return
      fi
      if [[ "$curword" == -* || "$curword" == "" ]]; then
        compadd -- -m --message --squash --no-ff \
          --push --no-push --no-fetch -h --help
      fi
      return
      ;;
    publish)
      case "${words[CURRENT-1]}" in
        -t|--title|-d|--description|-l|--label|-a|--assignee|\
        --reviewer)
          return
          ;;
      esac
      if [[ "$curword" == "--" ]]; then
        return
      fi
      if [[ "$curword" == -* || "$curword" == "" ]]; then
        compadd -- --no-fetch --no-push --fill -y --yes \
          --draft -t --title -d --description -l --label \
          -a --assignee --reviewer --remove-source-branch \
          -h --help
      fi
      return
      ;;
    config)
      if (( CURRENT == 3 )); then
        if [[ "$curword" == -* ]]; then
          compadd -- -h --help
        else
          compadd -- list set reset
        fi
        return
      fi
      case "${words[3]}" in
        list)
          [[ "$curword" == -* ]] && compadd -- -h --help
          return
          ;;
        set)
          if (( CURRENT == 4 )); then
            compadd -- merge.strategy merge.push
          elif (( CURRENT == 5 )); then
            case "${words[4]}" in
              merge.strategy)
                compadd -- squash merge
                ;;
              merge.push)
                compadd -- auto always never
                ;;
            esac
          fi
          return
          ;;
        reset)
          if (( CURRENT == 4 )); then
            compadd -- merge.strategy merge.push
          fi
          return
          ;;
      esac
      return
      ;;
    completion)
      if (( CURRENT == 3 )); then
        if [[ "$curword" == -* ]]; then
          compadd -- -h --help
        else
          compadd -- install uninstall status
        fi
        return
      fi
      case "${words[3]}" in
        install)
          if [[ "${words[CURRENT-1]}" == "--shell" ]]; then
            compadd -- bash zsh
          elif [[ "$curword" == -* || "$curword" == "" ]]; then
            compadd -- --shell --dry-run -h --help
          fi
          return
          ;;
        uninstall)
          if [[ "${words[CURRENT-1]}" == "--shell" ]]; then
            compadd -- bash zsh
          elif [[ "$curword" == -* || "$curword" == "" ]]; then
            compadd -- --shell -h --help
          fi
          return
          ;;
        status)
          [[ "$curword" == -* ]] && compadd -- -h --help
          return
          ;;
      esac
      return
      ;;
  esac
}

compdef _mr mr
