"""Shell completion scripts for ``mr`` and ``mr-diff`` (bash + zsh).

The scripts are printed by ``mr --print-completion {bash,zsh}`` and installed
with ``eval "$(mr --print-completion zsh)"``. Dynamic candidates (branch
refs, review files) are resolved in-shell with read-only ``git`` calls so
every ``<TAB>`` stays fast (no Python startup) and never fetches or writes.
"""

from __future__ import annotations

import sys
from collections.abc import Sequence

COMPLETION_SHELLS: tuple[str, ...] = ("bash", "zsh")
SUPPORTED_PROGRAMS: tuple[str, ...] = ("mr", "mr-diff")


def _mr_zsh_script() -> str:
    return """#compdef mr
# Auto-generated by `mr --print-completion zsh`. Install with:
#   eval "$(mr --print-completion zsh)"

__mr_branch_refs() {
  local -a refs
  local line
  refs=()
  for line in ${(f)"$(command git branch \\
      --format='%(refname:short)' 2>/dev/null)"} \\
      ${(f)"$(command git branch -r \\
      --format='%(refname:short)' 2>/dev/null)"}; do
    [[ -z "$line" || "$line" == *' -> '* ]] && continue
    refs+=("$line")
  done
  refs=(${(u)refs})
  compadd -a refs
}

_mr() {
  local curcontext="$curcontext" state line
  typeset -A opt_args
  local curword
  curword="${words[CURRENT]}"

  if (( CURRENT == 2 )); then
    if [[ "$curword" == -* ]]; then
      compadd -- --print-completion -h --help
    else
      compadd -- new base rebase reset merge publish config
    fi
    return
  fi

  if [[ "${words[2]}" == "--print-completion" ]]; then
    if (( CURRENT == 3 )); then
      compadd -- bash zsh
    fi
    return
  fi

  case "${words[2]}" in
    new)
      if [[ "$curword" == -* ]]; then
        compadd -- --no-fetch -h --help
      elif (( CURRENT == 3 )); then
        return
      elif (( CURRENT == 4 )); then
        __mr_branch_refs
      fi
      return
      ;;
    base)
      if (( CURRENT == 3 )); then
        if [[ "$curword" == -* ]]; then
          compadd -- -h --help
        else
          compadd -- set reset default
        fi
        return
      fi
      case "${words[3]}" in
        set)
          if [[ "$curword" == -* ]]; then
            compadd -- --no-fetch -h --help
          elif (( CURRENT == 4 )); then
            __mr_branch_refs
          fi
          return
          ;;
        reset)
          [[ "$curword" == -* ]] && compadd -- -h --help
          return
          ;;
        default)
          if (( CURRENT == 4 )); then
            if [[ "$curword" == -* ]]; then
              compadd -- -h --help
            else
              compadd -- set reset
            fi
            return
          fi
          case "${words[4]}" in
            set)
              if [[ "$curword" == -* ]]; then
                compadd -- --no-fetch -h --help
              elif (( CURRENT == 5 )); then
                __mr_branch_refs
              fi
              ;;
            reset)
              [[ "$curword" == -* ]] && compadd -- -h --help
              ;;
          esac
          return
          ;;
      esac
      return
      ;;
    rebase)
      if [[ "${words[CURRENT-1]}" == "--onto" ]]; then
        __mr_branch_refs
        return
      fi
      if [[ "$curword" == -* || "$curword" == "" ]]; then
        compadd -- --onto --continue --skip --abort \\
          --no-fetch -h --help
      fi
      return
      ;;
    reset)
      if [[ "$curword" == -* || "$curword" == "" ]]; then
        compadd -- --soft --mixed --hard --no-fetch -h --help
      fi
      return
      ;;
    merge)
      if [[ "${words[CURRENT-1]}" == "-m" || \\
          "${words[CURRENT-1]}" == "--message" ]]; then
        return
      fi
      if [[ "$curword" == -* || "$curword" == "" ]]; then
        compadd -- -m --message --squash --no-ff \\
          --push --no-push --no-fetch -h --help
      fi
      return
      ;;
    publish)
      case "${words[CURRENT-1]}" in
        -t|--title|-d|--description|-l|--label|-a|--assignee|\\
        --reviewer)
          return
          ;;
      esac
      if [[ "$curword" == "--" ]]; then
        return
      fi
      if [[ "$curword" == -* || "$curword" == "" ]]; then
        compadd -- --no-fetch --no-push --fill -y --yes \\
          --draft -t --title -d --description -l --label \\
          -a --assignee --reviewer --remove-source-branch \\
          -h --help
      fi
      return
      ;;
    config)
      if (( CURRENT == 3 )); then
        if [[ "$curword" == -* ]]; then
          compadd -- -h --help
        else
          compadd -- list set reset
        fi
        return
      fi
      case "${words[3]}" in
        list)
          [[ "$curword" == -* ]] && compadd -- -h --help
          return
          ;;
        set)
          if (( CURRENT == 4 )); then
            compadd -- merge.strategy merge.push
          elif (( CURRENT == 5 )); then
            case "${words[4]}" in
              merge.strategy)
                compadd -- squash merge
                ;;
              merge.push)
                compadd -- auto always never
                ;;
            esac
          fi
          return
          ;;
        reset)
          if (( CURRENT == 4 )); then
            compadd -- merge.strategy merge.push
          fi
          return
          ;;
      esac
      return
      ;;
  esac
}

compdef _mr mr
"""


def _mr_bash_script() -> str:
    return """# Auto-generated by `mr --print-completion bash`. Install with:
#   eval "$(mr --print-completion bash)"

__mr_branch_refs() {
  local cur="$1" refs
  refs="$( { command git branch --format='%(refname:short)' \\
    2>/dev/null; command git branch -r \\
    --format='%(refname:short)' 2>/dev/null | grep -v -- ' -> '; } \\
    | sort -u )"
  COMPREPLY=( $(compgen -W "$refs" -- "$cur") )
}

_mr_completion() {
  local cur prev cword
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  cword="$COMP_CWORD"

  if [[ "$cword" -eq 1 ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "--print-completion -h --help" \\
        -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "new base rebase reset merge \\
        publish config" -- "$cur") )
    fi
    return 0
  fi

  if [[ "${COMP_WORDS[1]}" == "--print-completion" ]]; then
    if [[ "$cword" -eq 2 ]]; then
      COMPREPLY=( $(compgen -W "bash zsh" -- "$cur") )
    fi
    return 0
  fi

  case "${COMP_WORDS[1]}" in
    new)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "--no-fetch -h --help" -- "$cur") )
      elif [[ "$cword" -eq 2 ]]; then
        COMPREPLY=()
      elif [[ "$cword" -eq 3 ]]; then
        __mr_branch_refs "$cur"
      fi
      return 0
      ;;
    base)
      if [[ "$cword" -eq 2 ]]; then
        if [[ "$cur" == -* ]]; then
          COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
        else
          COMPREPLY=( $(compgen -W "set reset default" -- "$cur") )
        fi
        return 0
      fi
      case "${COMP_WORDS[2]}" in
        set)
          if [[ "$cur" == -* ]]; then
            COMPREPLY=( $(compgen -W "--no-fetch -h --help" \\
              -- "$cur") )
          elif [[ "$cword" -eq 3 ]]; then
            __mr_branch_refs "$cur"
          fi
          return 0
          ;;
        reset)
          COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
          return 0
          ;;
        default)
          if [[ "$cword" -eq 3 ]]; then
            COMPREPLY=( $(compgen -W "set reset" -- "$cur") )
            return 0
          fi
          if [[ "${COMP_WORDS[3]}" == "set" ]]; then
            if [[ "$cur" == -* ]]; then
              COMPREPLY=( $(compgen -W "--no-fetch -h --help" \\
                -- "$cur") )
            elif [[ "$cword" -eq 4 ]]; then
              __mr_branch_refs "$cur"
            fi
          fi
          return 0
          ;;
      esac
      return 0
      ;;
    rebase)
      if [[ "$prev" == "--onto" ]]; then
        __mr_branch_refs "$cur"
        return 0
      fi
      COMPREPLY=( $(compgen -W "--onto --continue --skip --abort \\
        --no-fetch -h --help" -- "$cur") )
      return 0
      ;;
    reset)
      COMPREPLY=( $(compgen -W "--soft --mixed --hard --no-fetch \\
        -h --help" -- "$cur") )
      return 0
      ;;
    merge)
      if [[ "$prev" == "-m" || "$prev" == "--message" ]]; then
        COMPREPLY=()
        return 0
      fi
      COMPREPLY=( $(compgen -W "-m --message --squash --no-ff \\
        --push --no-push --no-fetch -h --help" -- "$cur") )
      return 0
      ;;
    publish)
      case "$prev" in
        -t|--title|-d|--description|-l|--label|-a|--assignee|\\
        --reviewer)
          COMPREPLY=()
          return 0
          ;;
      esac
      COMPREPLY=( $(compgen -W "--no-fetch --no-push --fill -y \\
        --yes --draft -t --title -d --description -l --label -a \\
        --assignee --reviewer --remove-source-branch -h --help" \\
        -- "$cur") )
      return 0
      ;;
    config)
      if [[ "$cword" -eq 2 ]]; then
        COMPREPLY=( $(compgen -W "list set reset" -- "$cur") )
        return 0
      fi
      case "${COMP_WORDS[2]}" in
        set)
          if [[ "$cword" -eq 3 ]]; then
            COMPREPLY=( $(compgen -W "merge.strategy merge.push" \\
              -- "$cur") )
          elif [[ "$cword" -eq 4 ]]; then
            case "${COMP_WORDS[3]}" in
              merge.strategy)
                COMPREPLY=( $(compgen -W "squash merge" -- "$cur") )
                ;;
              merge.push)
                COMPREPLY=( $(compgen -W "auto always never" \\
                  -- "$cur") )
                ;;
            esac
          fi
          return 0
          ;;
        reset)
          if [[ "$cword" -eq 3 ]]; then
            COMPREPLY=( $(compgen -W "merge.strategy merge.push" \\
              -- "$cur") )
          fi
          return 0
          ;;
      esac
      return 0
      ;;
  esac
}

complete -F _mr_completion mr
"""


def _mr_diff_zsh_script() -> str:
    return """#compdef mr-diff
# Auto-generated by `mr-diff --print-completion zsh`. Install with:
#   eval "$(mr-diff --print-completion zsh)"

__mr_diff_files() {
  local -a files
  local out
  out="$(command mr-diff list --name-only 2>/dev/null)"
  if [[ -n "$out" ]]; then
    files=(${(f)out})
  else
    files=(${(f)"$(command git ls-files 2>/dev/null)"} \\
      ${(f)"$(command git ls-files --others --exclude-standard \\
      2>/dev/null)"})
  fi
  compadd -a files
}

_mr_diff() {
  local curcontext="$curcontext" state line
  typeset -A opt_args
  local curword
  curword="${words[CURRENT]}"

  if (( CURRENT == 2 )); then
    if [[ "$curword" == -* ]]; then
      compadd -- --print-completion -h --help
    else
      compadd -- list file
    fi
    return
  fi

  if [[ "${words[2]}" == "--print-completion" ]]; then
    if (( CURRENT == 3 )); then
      compadd -- bash zsh
    fi
    return
  fi

  case "${words[2]}" in
    list)
      [[ "$curword" == -* ]] && compadd -- --name-only -h --help
      return
      ;;
    file)
      if [[ "$curword" == -* ]]; then
        compadd -- -h --help
      elif (( CURRENT == 3 )); then
        __mr_diff_files
      fi
      return
      ;;
  esac
}

compdef _mr_diff mr-diff
"""


def _mr_diff_bash_script() -> str:
    return """# Auto-generated by `mr-diff --print-completion bash`. Install:
#   eval "$(mr-diff --print-completion bash)"

__mr_diff_files() {
  local cur="$1" out files
  out="$(command mr-diff list --name-only 2>/dev/null)"
  if [[ -z "$out" ]]; then
    out="$( { command git ls-files 2>/dev/null; command git \\
      ls-files --others --exclude-standard 2>/dev/null; } \\
      | sort -u )"
  fi
  files="$out"
  COMPREPLY=( $(compgen -W "$files" -- "$cur") )
}

_mr_diff_completion() {
  local cur cword
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  cword="$COMP_CWORD"

  if [[ "$cword" -eq 1 ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "--print-completion -h --help" \\
        -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "list file" -- "$cur") )
    fi
    return 0
  fi

  if [[ "${COMP_WORDS[1]}" == "--print-completion" ]]; then
    if [[ "$cword" -eq 2 ]]; then
      COMPREPLY=( $(compgen -W "bash zsh" -- "$cur") )
    fi
    return 0
  fi

  case "${COMP_WORDS[1]}" in
    list)
      COMPREPLY=( $(compgen -W "--name-only -h --help" -- "$cur") )
      return 0
      ;;
    file)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
      elif [[ "$cword" -eq 2 ]]; then
        __mr_diff_files "$cur"
      fi
      return 0
      ;;
  esac
}

complete -F _mr_diff_completion mr-diff
"""


def render_completion(prog: str, shell: str) -> str:
    """Return the completion script for *prog* (``mr``|``mr-diff``)."""
    if prog not in SUPPORTED_PROGRAMS:
        raise ValueError(f"unknown program '{prog}' (expected mr|mr-diff)")
    if shell not in COMPLETION_SHELLS:
        raise ValueError(f"unknown shell '{shell}' (expected bash|zsh)")
    if prog == "mr":
        return _mr_zsh_script() if shell == "zsh" else _mr_bash_script()
    return _mr_diff_zsh_script() if shell == "zsh" else _mr_diff_bash_script()


def print_completion(prog: str, shell: str) -> int:
    """Print the completion script; return 0 or 2 on bad shell/program."""
    try:
        script = render_completion(prog, shell)
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    sys.stdout.write(script)
    if not script.endswith("\n"):
        sys.stdout.write("\n")
    return 0


def handle_print_completion(prog: str, argv: Sequence[str] | None) -> int | None:
    """Pre-scan *argv* for ``--print-completion``; print and return exit code.

    Returns None when the flag is absent so the caller continues with normal
    argparse dispatch. Supports ``--print-completion SHELL`` and
    ``--print-completion=SHELL``. Runs before ``parse_args`` because the
    subparsers are ``required=True`` and would otherwise reject a bare flag.
    Only honors the flag as the first argument so ``mr new x``-style calls
    are never hijacked.
    """
    args = list(sys.argv[1:] if argv is None else argv)
    if not args:
        return None
    first = args[0]
    shell: str | None = None
    if first == "--print-completion":
        if len(args) < 2:
            print("error: --print-completion needs bash|zsh", file=sys.stderr)
            return 2
        shell = args[1]
    elif first.startswith("--print-completion="):
        shell = first.partition("=")[2]
    else:
        return None
    if not shell:
        print("error: --print-completion needs bash|zsh", file=sys.stderr)
        return 2
    return print_completion(prog, shell)
